-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		icons = {
			boosts = {
				coin_boost = "rbxassetid://15294309561",
				lucky_boost = "rbxassetid://15294309649",
				stars_boost = "rbxassetid://15294309714",
				strength_boost = "rbxassetid://15294309767",
			},
			hand_click = "rbxassetid://15277603766",
			rebirth = "rbxassetid://15295231883",
			sword_outline = "rbxassetid://15277603950",
		},
		ui = {
			attack_button_base = "rbxassetid://15281857202",
			blur = "rbxassetid://15255783123",
			hud_bottom_curve = "rbxassetid://15278324050",
			rounded_button_base = "rbxassetid://15267940299",
		},
	},
}