-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		icons = {
			boost = "rbxassetid://15302168656",
			boosts = {
				coin_boost = "rbxassetid://15294309561",
				lucky_boost = "rbxassetid://15294309649",
				stars_boost = "rbxassetid://15294309714",
				strength_boost = "rbxassetid://15294309767",
			},
			coin = "rbxassetid://15303269882",
			daily_rewards = "rbxassetid://15302168729",
			fish = "rbxassetid://15302657608",
			hand_click = "rbxassetid://15277603766",
			inventory = "rbxassetid://15302168817",
			mission = "rbxassetid://15302522396",
			rebirth = "rbxassetid://15295231883",
			settings = "rbxassetid://15302168932",
			star = "rbxassetid://15303269918",
			sword_outline = "rbxassetid://15277603950",
			twitter = "rbxassetid://15302169045",
		},
		ui = {
			attack_button_base = "rbxassetid://15281857202",
			blur = "rbxassetid://15255783123",
			hud_arrow = "rbxassetid://15302522438",
			hud_bottom_curve = "rbxassetid://15278324050",
			rounded_button_base = "rbxassetid://15267940299",
			stats_bar_base = "rbxassetid://15303347451",
			stats_bar_coin = "rbxassetid://15303347522",
			stats_bar_stars = "rbxassetid://15303347597",
		},
	},
}